# Generated by Django 6.0 on 2026-01-09 01:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.CharField(max_length=200)),
                ('aplicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=10)),
                ('Cajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Caja.cajero')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Management'), (2, 'Assistant')], default=2, verbose_name='Admin type')),
                ('Cajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Caja.cajero')),
            ],
        ),
        migrations.CreateModel(
            name='ingresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, default='Reposición de caja chica')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.caja')),
            ],
        ),
    ]
