# Generated by Django 6.0.2 on 2026-04-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='numRepos',
        ),
    ]
