# Generated by Django 6.0 on 2025-12-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='proveedor',
            new_name='Departamento',
        ),
    ]
