# Generated by Django 6.0 on 2026-01-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='descripcion',
            field=models.TextField(default='Reposición de caja chica'),
        ),
    ]
