# Generated by Django 6.0.2 on 2026-04-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_remove_factura_numrepos'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numRepos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Caja.ingresocaja'),
        ),
    ]
