# Generated by Django 6.0 on 2025-12-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_rename_proveedor_departamento_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='departamento',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
