# Generated by Django 6.0 on 2026-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_alter_ingresocaja_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='descripcion',
            field=models.TextField(blank=True, default='Reposición de caja chica'),
        ),
    ]
