# Generated by Django 6.0 on 2025-12-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0003_alter_factura_departamento_delete_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='aplicada',
            field=models.BooleanField(default=False),
        ),
    ]
