# Generated by Django 6.0.2 on 2026-05-25 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0004_usuario_admin_usuario_idx_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numRepos',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10),
        ),
    ]
