# Generated by Django 6.0 on 2025-12-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0004_factura_aplicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=8000.0, max_digits=10),
        ),
    ]
