# Generated by Django 6.0 on 2025-12-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0005_caja_saldo_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.caja')),
            ],
        ),
    ]
