# Generated by Django 6.0 on 2025-12-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0006_ingresocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.caja')),
            ],
        ),
    ]
