# Generated by Django 6.0.2 on 2026-05-25 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0006_ingresocaja_numrepos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numRepos',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='ingresocaja',
            name='numRepos',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20),
        ),
    ]
