# Generated by Django 6.0 on 2025-12-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_bitacora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bitacora',
        ),
    ]
