# Generated by Django 6.0.2 on 2026-05-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_alter_factura_numrepos_alter_ingresocaja_numrepos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='facturs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Caja.factura'),
        ),
    ]
