# Generated by Django 6.0.2 on 2026-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0008_alter_ingresocaja_facturs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='facturs',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
