# Generated by Django 6.0 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0009_generar_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='generar_reporte',
        ),
    ]
