# Generated by Django 6.0 on 2026-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0009_alter_ingresocaja_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='descripcion',
            field=models.CharField(default='Reposicion de caja chica', max_length=255),
            preserve_default=False,
        ),
    ]
