# Generated by Django 6.0.2 on 2026-05-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0009_alter_ingresocaja_facturs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='ingresocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.factura'),
        ),
    ]
