# Generated by Django 6.0 on 2026-01-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0010_alter_ingresocaja_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocaja',
            name='descripcion',
            field=models.CharField(default='Reposición de caja', max_length=255),
        ),
    ]
