# Generated by Django 6.0.2 on 2026-05-28 06:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0010_rename_description_factura_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numRepos',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=99),
        ),
        migrations.AlterField(
            model_name='ingresocaja',
            name='numRepos',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=99),
        ),
    ]
