# Generated by Django 6.0 on 2025-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0010_reg_bitacora_delete_generar_reporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_bitacora',
        ),
    ]
