# Generated by Django 6.0 on 2026-01-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0011_delete_reg_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='saldo',
        ),
    ]
