# Generated by Django 6.0.2 on 2026-05-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0011_alter_factura_numrepos_alter_ingresocaja_numrepos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresocaja',
            old_name='monto',
            new_name='importe',
        ),
        migrations.RenameField(
            model_name='ingresocaja',
            old_name='facturs',
            new_name='numFact',
        ),
    ]
