# Generated by Django 6.0.2 on 2026-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0012_rename_monto_ingresocaja_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numRepos',
            field=models.CharField(default='0', max_length=55),
        ),
        migrations.AlterField(
            model_name='ingresocaja',
            name='numRepos',
            field=models.CharField(default='0', max_length=55),
        ),
    ]
