# Generated by Django 6.0.6 on 2026-06-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0013_alter_factura_numrepos_alter_ingresocaja_numrepos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(choices=[('FALTANTE_ARQUEO', 'Faltante en Arqueo de Caja'), ('ANTICIPO', 'Anticipo / Préstamo Corto'), ('OTRO', 'Otro Motivo Descriptivo')], default='FALTANTE_ARQUEO', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Detalles del descuadre o aclaraciones', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Descuento'), ('APLICADO', 'Descontado en Nómina'), ('CANCELADO', 'Cancelado / Sin Efecto')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, help_text='Fecha en que nómina aplicó el descuento', null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales', to='Caja.caja')),
                ('usuario_autoriza', models.ForeignKey(help_text='Supervisor que detectó o autorizó el vale', on_delete=django.db.models.deletion.PROTECT, related_name='vales_autorizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_recibe', models.ForeignKey(help_text='Cajero responsable del faltante o deudor', on_delete=django.db.models.deletion.PROTECT, related_name='vales_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
