# Generated by Django 6.0 on 2026-01-08 04:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0013_caja_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=10),
        ),
    ]
