# Generated by Django 6.0.6 on 2026-06-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0014_valecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecaja',
            name='usuario_autoriza',
            field=models.ForeignKey(help_text='Supervisor que detectó o autorizó el vale', on_delete=django.db.models.deletion.PROTECT, related_name='vales_autorizados', to='Caja.usuario'),
        ),
        migrations.AlterField(
            model_name='valecaja',
            name='usuario_recibe',
            field=models.ForeignKey(help_text='Cajero responsable del faltante o deudor', on_delete=django.db.models.deletion.PROTECT, related_name='vales_recibidos', to='Caja.usuario'),
        ),
    ]
