# Generated by Django 6.0 on 2026-01-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0014_alter_caja_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.IntegerField(default=8000),
        ),
    ]
