# Generated by Django 6.0.6 on 2026-06-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0016_alter_valecaja_usuario_autoriza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='Caja.caja'),
        ),
    ]
