# Generated by Django 6.0.6 on 2026-06-23 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0017_alter_valecaja_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecaja',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Descuento'), ('APLICADO', 'Descontado en Nómina'), ('CANCELADO', 'Cancelado / Sin Efecto'), ('SIN EFECTO', 'Cancelado / Sin Efecto')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ALTA', 'Alta de Registro'), ('BAJA', 'Baja de Registro'), ('CAMBIO', 'Modificación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ARQUEO', 'Arqueo de Caja'), ('REPOSICION', 'Reposición de Fondos'), ('ERROR', 'Fallo o Excepción en Sistema')], max_length=20)),
                ('modulo', models.CharField(help_text="Ej: 'cajeros', 'cajas', 'facturas', 'acceso'", max_length=50)),
                ('descripcion', models.TextField(help_text='Detalle legible de lo que se hizo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado (Ej: id_factura)', null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
